# Configuration file for the Discord Relay plugin

# Discord bot token (keep this secret!)
discord-bot-token: "YOUR_BOT_TOKEN_HERE"

# Discord channel ID for relaying messages
join-leave-channel-id: "YOUR_CHANNEL_ID_HERE"

chat-channel-id: "YOUR_CHANNEL_ID_HERE"

death-channel-id: "YOUR_CHANNEL_ID_HERE"

playerlist-channel-id: "YOUR_CHANNEL_ID_HERE"

# Discord CHANNEL or THREAD
channel-type: "CHANNEL"

# If you have many servers, add to prefix with relaying messages

server-prefix-id: "YOUR_SERVER_PREFIX_ID_HERE"